version: '2.1'

services:
  awsemulators.demo.consoleapp:
    image: awsemulators.demo.consoleapp
    build:
      context: .
      dockerfile: ConsoleApp/Dockerfile
    environment:
      - YANS_AWS_ACCESS_KEY
      - YANS_AWS_SECRET_KEY
    volumes:
      - ./ConsoleApp/Configurations:/Configuration
  localstack:
     extends:
        file: localstack-compose.yml     
        service: localstack
  portainer:
     extends:
        file: portainer-compose.yml
        service: portainer
#  goaws:
#     extends:
#        file: GoAws-compose.yml
#        service: goaws